In [29]:
import numpy as np
data1 = np.array([1,2,3,4,5])
#print(data1)
data2 = np.array([[1,2],
                  [3,4]])
#print(data2)
#print("\n")
#维度
#print(data1.shape,data2.shape,"\n")
#空矩阵
#print(np.zeros([2,3]),"\n"*2,np.ones([2,2]))
#矩阵 改
data2[1,0] = 5
#print(data2)
#矩阵查
#print(data2[1,1])
#数和矩阵 基本运算 
data3 = np.ones([2,3])
#print(data3*2)
#print(data3/3)
#print(data3+2)
#print(data3-1)
#矩阵的+ *
data4 = np.array([[1,2,3],[4,5,6]])
print(data3+data4)
print(data3*data4)

[[2. 3. 4.]
 [5. 6. 7.]]
[[1. 2. 3.]
 [4. 5. 6.]]
